# Generated by Django 3.2.7 on 2021-09-19 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transapp', '0002_alter_agent_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='agent_id',
            new_name='agent',
        ),
    ]
