# Generated by Django 3.2.7 on 2021-09-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transapp', '0003_rename_agent_id_transaction_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(),
        ),
    ]
